name: Deploy to EC2

on:
  push:
    branches:
      - main  # or use "master" if your branch is named that

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t otarbakhtadze/skydeploy:latest .
        docker push otarbakhtadze/skydeploy:latest

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull otarbakhtadze/skydeploy:latest
          docker stop skydeploy || true
          docker rm skydeploy || true
          docker run -d -p 5000:5000 --name skydeploy otarbakhtadze/skydeploy:latest
